[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "gencf"
version = "0.2.0"
description = "A package to determine non-vanishing crystal field parameters from point group symmetries."
readme = "README.md"
requires-python = ">=3.10"
license = {text = "MIT"}
authors = [
    {name = "Li Hong Liu"}
]
keywords = ["crystal-field", "quantum"]
dependencies = [
    "numpy>=1.20.0",
    "sympy>=1.14.0",
    "tabulate>=0.9.0"
]
classifiers = [
    "Intended Audience :: Science/Research",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3.10",
]

[project.urls]
Homepage = "https://github.com/Quantum-Integration-Laboratory/gencf"
Repository = "https://github.com/Quantum-Integration-Laboratory/gencf.git"
Issues = "https://github.com/Quantum-Integration-Laboratory/gencf/issues"

[project.optional-dependencies]
test = [
    "pytest>=8.0",
]

[tool.setuptools]
packages = ["gencf"]
